[project]
name = 'PrescriptionDrugTracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.authenticity-verifier]
path = 'contracts/authenticity-verifier.clar'
clarity_version = 3
epoch = 3.1

[contracts.drug-registry]
path = 'contracts/drug-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.supply-tracker]
path = 'contracts/supply-tracker.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
